# Generated by Django 4.2.30 on 2026-05-08 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_text', models.TextField(verbose_name='News Text')),
                ('verdict', models.CharField(blank=True, choices=[('fake', 'Fake'), ('real', 'Real'), ('uncertain', 'Uncertain')], max_length=20, verbose_name='Verdict')),
                ('confidence', models.IntegerField(default=0, verbose_name='Confidence (%)')),
                ('reasoning', models.TextField(blank=True, verbose_name='AI Reasoning')),
                ('language_used', models.CharField(default='en', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analysis',
                'verbose_name_plural': 'Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
